<a class="btn btn-success" href="<?php echo  $this->url(array(),'uploader'); ?>"><i class="icon-white icon-upload"></i> <?php echo $this->translate('upload');?></a>
<a class="btn btn-success" href="/locale"><?php echo $this->translate('locale');?></a>
<a class="btn btn-success" href="<?php echo $this->url(array('module'=>'default','controller'=>'transalte','action'=>'index'),'default','true');?>"> <?php echo $this->translate('translate');?></a>
<a class="btn btn-success" href="<?php echo $this->url(array('module'=>'default','controller'=>'dbtest','action'=>'index'),'default','true');?>"> <?php echo $this->translate('database');?></a>
<br><br><br>