<a class="btn btn-success" href="<?= $this->url(array(),'uploader'); ?>"><i class="icon-white icon-upload"></i> <?=$this->translate('upload');?></a>
<a class="btn btn-success" href="/locale"><?=$this->translate('locale');?></a>
<a class="btn btn-success" href="<?=$this->url(array('module'=>'default','controller'=>'transalte','action'=>'index'),'default','true');?>"> <?=$this->translate('translate');?></a>
<a class="btn btn-success" href="<?=$this->url(array('module'=>'default','controller'=>'dbtest','action'=>'index'),'default','true');?>"> <?=$this->translate('database');?></a>
<br><br><br>